name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to Production
      run: ng build --prod
